"""add wallet and transaction tables

Revision ID: e205dfad8bdc
Revises: d47c165a9711
Create Date: 2026-07-01 09:45:46.846339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e205dfad8bdc'
down_revision: Union[str, None] = 'd47c165a9711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
